#ifndef MAIN_INCLUDE
#include "./hashMethod/MD/MD2.cc"
#include "./hashMethod/MD/MD4.cc"
#include "./hashMethod/MD/MD5.cc"
#include "./hashMethod/MD/MD5X.cc"
#include "./hashMethod/SHA/SHA-1.cc"
#include "./hashMethod/SHA/SHA-224.cc"
#include "./hashMethod/SHA/SHA-256.cc"
#include "./hashMethod/SHA/SHA-384.cc"
#include "./hashMethod/SHA/SHA-512.cc"
#include "./hashMethod/RIPEMD/RIPEMD-128.cc"
#include "./hashMethod/RIPEMD/RIPEMD-160.cc"
#include "./hashMethod/RIPEMD/RIPEMD-256.cc"
#include "./hashMethod/RIPEMD/RIPEMD-320.cc"
#include "./hashMethod/HAVAL/HAVAL-3.cc"
#include "./hashMethod/HAVAL/HAVAL-4.cc"
#include "./hashMethod/HAVAL/HAVAL-5.cc"
#define MAIN_INCLUDE
#endif